[project]
name = "fastapi-example-base-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.120.0",
    "pydantic-settings>=2.11.0",
    "pydantic[email]>=2.12.3",
]
